import MainPadrao from "@/components/main-padrao/main-padrao";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Luand App",
	description: "Generated by create next app",
};

export default function EmpresaLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return <MainPadrao>{children}</MainPadrao>;
}
