import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const beVietnamProFont = Be_Vietnam_Pro({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Luand App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="pt-br">
			<body className={`${beVietnamProFont.className} flex flex-col items-center text-primary bg-white`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
